/*
 * ultrasonic.c
 *
 *  Created on: Mar 4, 2024
 *      Author: youssef
 */
#include "ultrasonic.h"
#include "icu.h"
#include"gpio.h"
#include <util/delay.h>

#define F_CPU 8000000UL

uint8 edge_count=0;
uint16 ultrasonic_time=0;

void Ultrasonic_init(void){
	ICU_setCallBack(Ultrasonic_edgeProcessing);  // set the call back function
	ICU_ConfigType ICU_Configurations = {F_CPU_8,RAISING}; // setup the configuration of the icu
	ICU_init(&ICU_Configurations);
	GPIO_setupPinDirection(TRIGGER_PORT_ID,TRIGGER_PIN_ID,PIN_OUTPUT);

}
/*
 *  Description
    ➢ Initialize the ICU driver as required.
    ➢ Setup the ICU call back function.
    ➢ Setup the direction for the trigger pin as output pin through the
       GPIO driver.
• Inputs: None
• Return: None
 */






void Ultrasonic_Trigger(void){
	// send the trigger pulse to the sensor
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_LOW);

}
/*
  * Description
       ➢ Send the Trigger pulse to the ultrasonic.
       • Inputs: None
       • Return: None
*/






uint16 Ultrasonic_readDistance(void){
	Ultrasonic_Trigger();
	while(edge_count!=2);
	edge_count = 0;
	return (uint16)((uint32)ultrasonic_time*0.0174);





}

/* Description
      ➢ Send the trigger pulse by using Ultrasonic_Trigger function.
      ➢ Start the measurements by the ICU from this moment.
        • Inputs: None
        • Return: The measured distance in Centimeter.
 */




void Ultrasonic_edgeProcessing(void){
	edge_count++;
	if(edge_count==1){
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(FALLING);
	}
	else if (edge_count==2){
		ultrasonic_time = ICU_getInputCaptureValue();
		ICU_setEdgeDetectionType(RAISING);
	}

}



/*
 * Description
   ➢ This is the call back function called by the ICU driver.
    ➢ This is used to calculate the high time (pulse time) generated by
         the ultrasonic sensor.
• Inputs: None
• Return: None
 */
